micronaut:
  application:
    name: bookMicroservice
datasources:
  default:
#    DOCKER_HOST=tcp://localhost:2375
    url: jdbc:mariadb://localhost:3306/books
    username: todo
    password: todosecret
    driver-class-name: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages:
        - uk.ac.york.eng2.books.domain
    properties:
      hibernate:
        hbm2ddl:
          auto: update
kafka:
  bootstrap:
    servers: ${KAFKA_BOOTSTRAP_SERVERS:`localhost:9094`}
